export const MESSAGE_TYPES = {
  START_SCAN: "START_SCAN",
  DETECT_PAGE: "DETECT_PAGE",
  SCAN_SEARCH_RESULTS: "SCAN_SEARCH_RESULTS",
  PROFILE_PAGE_READY: "PROFILE_PAGE_READY",
  VERIFY_PROFILE: "VERIFY_PROFILE",
  PROFILE_VERIFIED: "PROFILE_VERIFIED",
  CAPTURE_ACTIVITY_SNAPSHOT: "CAPTURE_ACTIVITY_SNAPSHOT",
};
